### ISSUE TITLE
ConnectionClosed error on ops_test cleanup

### ISSUE THREAD

**Issue by PietroPasotti** [charmed-kubernetes/pytest-operator#71] opened 2022-04-14 14:10 UTC
In a charm I'm developing, my itests are failing because of an uncaught websockets.exceptions.ConnectionClosed error.
I tried figuring out what was going on but had little luck. It looks like something goes wrong when trying to destroy the test model in `ops_test._cleanup_models()`.

Attaching a full debug log.
`$ tox -vve integration > itest_logs.txt`

[itest_logs.txt](https://github.com/charmed-kubernetes/pytest-operator/files/8489809/itest_logs.txt)

**Comment by addyess** [comment] 2022-04-19 15:57
Closing as a duplicate of https://github.com/charmed-kubernetes/pytest-operator/issues/72

**Closed by addyess** 2022-04-19 15:57 UTC
